"""remove sla_escalado_em

Revision ID: 9d477ecbc972
Revises: bfb3e3298cb4
Create Date: 2026-06-23 13:47:59.124254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d477ecbc972'
down_revision: Union[str, Sequence[str], None] = 'bfb3e3298cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('sla_escalado_em')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_escalado_em', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
