"""notificacoes, votos kb, templates, tags, sla config

Revision ID: a6202fd9f8c9
Revises: 9d477ecbc972
Create Date: 2026-06-23 14:46:16.373739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6202fd9f8c9'
down_revision: Union[str, Sequence[str], None] = '9d477ecbc972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('data')
    )
    op.create_table('parametros_sla',
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prioridade')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)

    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_lida'), ['lida'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('sistema_afetado', sa.String(length=80), nullable=True),
    sa.Column('impacto_negocio', sa.Enum('BAIXO', 'MEDIO', 'ALTO', 'CRITICO', name='impactonegocio'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_id'), ['id'], unique=False)

    op.create_table('chamado_tags',
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('chamado_id', 'tag_id')
    )
    op.create_table('artigo_votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('util', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artigo_id'], ['artigos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artigo_id', 'usuario_id')
    )
    with op.batch_alter_table('artigo_votos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artigo_votos_artigo_id'), ['artigo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artigo_votos_id'), ['id'], unique=False)

    # SQLite suporta ADD COLUMN simples para coluna anulável — evita o batch
    # (que recria a tabela e tropeça nos CHECK sem nome dos Enums). A FK fica
    # declarada no ORM; o SQLite não a exige no ADD COLUMN.
    op.add_column('chamados', sa.Column('mesclado_em_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'mesclado_em_id')

    with op.batch_alter_table('artigo_votos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artigo_votos_id'))
        batch_op.drop_index(batch_op.f('ix_artigo_votos_artigo_id'))

    op.drop_table('artigo_votos')
    op.drop_table('chamado_tags')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_id'))

    op.drop_table('templates')
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_lida'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_criado_em'))

    op.drop_table('notificacoes')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    op.drop_table('parametros_sla')
    op.drop_table('feriados')
    # ### end Alembic commands ###
