"""schema inicial

Revision ID: bfb3e3298cb4
Revises: 
Create Date: 2026-06-22 22:06:04.743717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb3e3298cb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_id'), ['id'], unique=False)

    op.create_table('contadores',
    sa.Column('chave', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('registros_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_rate_chave'), ['chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rate_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rate_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rate_tipo'), ['tipo'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso', sa.Enum('USUARIO', 'ADMINISTRADOR', name='nivelacesso'), nullable=False),
    sa.Column('papel', sa.Enum('COLABORADOR', 'ANALISTA', 'LIDER', 'COORDENADOR', 'ADMINISTRADOR', name='papel'), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('unidade_setor', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ramal', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_papel'), ['papel'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_supervisor_id'), ['supervisor_id'], unique=False)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=120), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_entidade_id'), ['entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategorias_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcategorias_id'), ['id'], unique=False)

    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_protocolo', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ANDAMENTO', 'AGUARDANDO_USUARIO', 'RESOLVIDO', 'FECHADO', 'REABERTO', 'CANCELADO', name='statuschamado'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('sistema_afetado', sa.String(length=80), nullable=True),
    sa.Column('modulo_tela', sa.String(length=120), nullable=True),
    sa.Column('impacto_negocio', sa.Enum('BAIXO', 'MEDIO', 'ALTO', 'CRITICO', name='impactonegocio'), nullable=True),
    sa.Column('urgencia_solicitante', sa.Integer(), nullable=True),
    sa.Column('unidade_setor', sa.String(length=120), nullable=True),
    sa.Column('contato_retorno', sa.String(length=120), nullable=True),
    sa.Column('indisponibilidade_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indisponibilidade_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gravidade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='gravidade'), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('qualidade_descritiva', sa.Enum('BOA', 'RUIM', name='qualidadedescritiva'), nullable=True),
    sa.Column('analise_ia_versao', sa.String(length=50), nullable=True),
    sa.Column('ia_confianca', sa.Float(), nullable=True),
    sa.Column('ia_justificativa', sa.Text(), nullable=True),
    sa.Column('ia_gravidade_sugerida', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='gravidade'), nullable=True),
    sa.Column('categoria_sugerida', sa.String(length=80), nullable=True),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('solucao_aplicada', sa.Text(), nullable=True),
    sa.Column('acao_preventiva', sa.Text(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('aberto_por_id', sa.Integer(), nullable=True),
    sa.Column('atribuido_a_id', sa.Integer(), nullable=True),
    sa.Column('sla_prazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_segundos_pausado', sa.Integer(), nullable=False),
    sa.Column('sla_pausado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_escalado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('versao_linha', sa.Integer(), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['atribuido_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamados_atribuido_a_id'), ['atribuido_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_gravidade'), ['gravidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_impacto_negocio'), ['impacto_negocio'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_numero_protocolo'), ['numero_protocolo'], unique=True)
        batch_op.create_index(batch_op.f('ix_chamados_status'), ['status'], unique=False)

    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_chamado_id'), ['chamado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anexos_id'), ['id'], unique=False)

    op.create_table('artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('chamado_origem_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamado_origem_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artigos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artigos_id'), ['id'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_chamado_id'), ['chamado_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_avaliacoes_id'), ['id'], unique=False)

    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('interno', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_chamado_id'), ['chamado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_comentarios_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_id'))
        batch_op.drop_index(batch_op.f('ix_comentarios_criado_em'))
        batch_op.drop_index(batch_op.f('ix_comentarios_chamado_id'))

    op.drop_table('comentarios')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_chamado_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('artigos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artigos_id'))

    op.drop_table('artigos')
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_id'))
        batch_op.drop_index(batch_op.f('ix_anexos_chamado_id'))

    op.drop_table('anexos')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamados_status'))
        batch_op.drop_index(batch_op.f('ix_chamados_numero_protocolo'))
        batch_op.drop_index(batch_op.f('ix_chamados_impacto_negocio'))
        batch_op.drop_index(batch_op.f('ix_chamados_id'))
        batch_op.drop_index(batch_op.f('ix_chamados_gravidade'))
        batch_op.drop_index(batch_op.f('ix_chamados_criado_em'))
        batch_op.drop_index(batch_op.f('ix_chamados_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_chamados_autor_id'))
        batch_op.drop_index(batch_op.f('ix_chamados_atribuido_a_id'))

    op.drop_table('chamados')
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategorias_id'))
        batch_op.drop_index(batch_op.f('ix_subcategorias_categoria_id'))

    op.drop_table('subcategorias')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_auditoria_acao'))

    op.drop_table('auditoria')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_papel'))
        batch_op.drop_index(batch_op.f('ix_usuarios_matricula'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('registros_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_rate_tipo'))
        batch_op.drop_index(batch_op.f('ix_registros_rate_id'))
        batch_op.drop_index(batch_op.f('ix_registros_rate_criado_em'))
        batch_op.drop_index(batch_op.f('ix_registros_rate_chave'))

    op.drop_table('registros_rate')
    op.drop_table('contadores')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_id'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
